### ISSUE TITLE
Special files are not extracted properly, even with fakeroot

### ISSUE THREAD

**Issue by shefft** [jrspruitt/ubi_reader#13]
Works fine as root (sudo).  With fakeroot, the flags are missed and it creates empty files only instead of char/block special files (devices).

diff -r --no-dereference ubifs-root/1365211099/rootfs/ realFS/
File ubifs-root/1365211099/rootfs/dev/console is a regular empty file while file realFS/dev/console is a character special file

Testing the mounted source file system - SHOULD SEE
ls -al realFS/dev/console
crw-r--r-- 1 root root 5, 1 Apr 18 23:30 realFS/dev/console
file realFS/dev/console 
realFS/dev/console: character special (5/1)

Instead, we have a problem
sudo ls -al ubifs-root/1365211099/rootfs/dev/console
-rw-r--r-- 1 ts ts 0 Oct 11 20:29 ubifs-root/1365211099/rootfs/dev/console
sudo file ubifs-root/1365211099/rootfs/dev/console
ubifs-root/1365211099/rootfs/dev/console: empty

**Comment by jrspruitt** [comment]
Hi, 
I did a little research and from what I can tell, fakeroot doesn't actually create devices, it just makes it look like it did. I did not know this, so I believe root or sudo should be used instead to get the actual special files. I will change the README.
-Jason

**Comment by shefft** [comment]
Yes, I was just about to redact this comment actually.  I've been looking into it.  The problem is not with the tool, it's simply misleading documentation.  Thanks!!  Great tool.

This is the best explanation on the topic I've managed to find.
http://www.embeddedlinux.org.cn/OEManual/fakeroot.html
