### ISSUE TITLE
Just wondering - is there a reason you haven't placed setup.py in the release archive?

### ISSUE THREAD

**Issue by shefft** [jrspruitt/ubi_reader#14]
Thanks for looking at my comments.

**Comment by shefft** [comment]
Guess it was added later?  Are you planning a release with setup.py included anytime soon?  Inquiring minds are curious!

**Comment by jrspruitt** [comment]
I forgot I ever put up releases, they were done before the setup.py install was added. Thanks for reminding me. I added both branches to releases.

-Jason
