### ISSUE TITLE
Would you mind adding a doc blurb about the number name of the folder to which files are extracted?

### ISSUE THREAD

**Issue by shefft** [jrspruitt/ubi_reader#15]
i.e. ubirootfs1/**1365211099**/rootfs

What is its significance?  Is there an option to extract directly to the specified path (-o) or are we left with the two levels down effect?

**Comment by jrspruitt** [comment]
It's the UBI image id, which is necessary if there is more than one UBI image in the data.

**Comment by shefft** [comment]
Ok, thanks for the clarification!  I see that now in the info display.
