### ISSUE TITLE
Feature req: preserve file dates

### ISSUE THREAD

**Issue by mefistotelis** [jrspruitt/ubi_reader#17]
The tool works great for the purpose it was created - allows extracting and re-creating damaged UbiFS.

One thing that is not preserved are file dates. While preserving permissions works great, dates of Access/Modify/Change are all set to the extraction date.

**Comment by jrspruitt** [comment]
Hi mefistotelis,

Not sure why this wasn't included, it is a good idea and a quick fix to add access and modify times. UBIFS also keeps creation timestamps, and all of them in either seconds or nanoseconds, I went with seconds, and left creation time out, as Linux/Unix does not support it apparently.

Thanks,
-Jason

**Comment by mefistotelis** [comment]
Yes, that's good implementation.

Works as expected. Thank you!
