### ISSUE TITLE
ubi reader and scripts are broken when intstalled in a python3 environment

### ISSUE THREAD

**Issue by smipi1** [jrspruitt/ubi_reader#18]
When installing ubi_reader in a python3 environment (E.g. Ubuntu 16.04 or newer), the scripts are broken.

ubi_reader is usually installed with
```
sudo pip install ubi_reader
```

This installs ubi_reader with a python3 shebang, resulting in the interpreter complaining about the python2 syntax:
```
$ ubireader_extract_images --help
  File "/usr/local/bin/ubireader_extract_images", line 38
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by jrspruitt** [comment]
Hi,

As of now ubi_reader does not work with Python 3, from what I can tell it will take significant fixes to make it happen because of the difference in how 3 and 2 use unicode, and I just haven't had time.

-Jason

**Comment by smipi1** [comment]
Hi Jason,

I'd be willing to give it a go. Do you have some test vectors for each of the scripts that I can use to verify that nothing breaks?

Is it okay if I perform a straight up conversion to python 3 without worrying about python 2 compatibility?

Regards,
Pieter

**Comment by jrspruitt** [comment]
Hi Peter,

That would be great. I believe the major issue was with struct unpack and then just some syntax issues like the error you got, should be Exception as e, then any print statements. It would be nice to have 2 and 3 working together, but from what I could tell it would probably be pretty messy, and add a lot of overhead. These parts of the script get called *a lot*. As for testing I just use a few random ubi/ubifs images, this should be good enough.

-Jason

**Comment by jrspruitt** [comment]
Thank you very much for getting this going, I've merged to master now, it passed all my usual extraction tests. I'll remove the Python3 branch, and work on getting a PyPi updated.

-Jason

**Comment by smipi1** [comment]
Thanks! Did you manage to figure out the performance regression?

**Comment by jrspruitt** [comment]
Unfortunately I could not figure it out, it has to do with byte string
concating, buf += decompress(..) or buf = b''.join([buf, decompress(..)])
which is supposed to be faster, were very similar. It was a huge difference
between 2 and 3, but it is possible it is my machine, as I could repeat it
in the Python3 console, where others could not.

**Comment by smipi1** [comment]
Did you check your exact Python version compared to others?

**Comment by jrspruitt** [comment]
No I didn't, I forgot to ask, I have the latest Debian, Cinnamon Desktop,
and Python 3.5.3.
