### ISSUE TITLE
compression parameter

### ISSUE THREAD

**Issue by novalisek** [jrspruitt/ubi_reader#19]
Hello,
it would be nice to also add parameter "-x"  to mkfs.ubifs when generating script using ubireader_utils_info. It corretly shows the "zlib" compression, but "-x zlib" is missing at the mkfs.ubifs line

Thanks.

**Comment by jrspruitt** [comment]
Hi,
I changed the script to include all the flags I could figure out the values for. Thanks for the suggestion.
-Jason

**Comment by novalisek** [comment]
thank you, it is perfect now
