### ISSUE TITLE
Fatal: PEB: 285: Bad Read Offset Request

### ISSUE THREAD

**Issue by Ansuel** [jrspruitt/ubi_reader#22]
I'm trying to decompress this file... it doesn't give me any crc error just this

guess_start_offset Found UBI magic number at 0
guess_filetype Looking for file type at 0
guess_filetype File looks like a UBI image.
UBI_File Open Path: 2C0000.ubi
UBI_File File Size: 37355540
UBI_File Start Offset: 0
UBI_File End Offset: 37355540
UBI_File Block Size: 131072
extract_blocks Block: PEB# 0: LEB# 0
extract_blocks Block: PEB# 1: LEB# 1
extract_blocks Block: PEB# 2: LEB# 0
extract_blocks Block: PEB# 3: LEB# 1
extract_blocks Block: PEB# 4: LEB# 2
extract_blocks Block: PEB# 5: LEB# 3
extract_blocks Block: PEB# 6: LEB# 4
extract_blocks Block: PEB# 7: LEB# 5
extract_blocks Block: PEB# 8: LEB# 6
extract_blocks Block: PEB# 9: LEB# 7
extract_blocks Block: PEB# 10: LEB# 8
extract_blocks Block: PEB# 11: LEB# 9
extract_blocks Block: PEB# 12: LEB# 10
extract_blocks Block: PEB# 13: LEB# 11
extract_blocks Block: PEB# 14: LEB# 12
extract_blocks Block: PEB# 15: LEB# 13
extract_blocks Block: PEB# 16: LEB# 14
extract_blocks Block: PEB# 17: LEB# 15
extract_blocks Block: PEB# 18: LEB# 16
extract_blocks Block: PEB# 19: LEB# 17
extract_blocks Block: PEB# 20: LEB# 18
extract_blocks Block: PEB# 21: LEB# 19
extract_blocks Block: PEB# 22: LEB# 20
extract_blocks Block: PEB# 23: LEB# 21
extract_blocks Block: PEB# 24: LEB# 22
extract_blocks Block: PEB# 25: LEB# 23
extract_blocks Block: PEB# 26: LEB# 24
extract_blocks Block: PEB# 27: LEB# 25
extract_blocks Block: PEB# 28: LEB# 26
extract_blocks Block: PEB# 29: LEB# 27
extract_blocks Block: PEB# 30: LEB# 28
extract_blocks Block: PEB# 31: LEB# 29
extract_blocks Block: PEB# 32: LEB# 30
extract_blocks Block: PEB# 33: LEB# 31
extract_blocks Block: PEB# 34: LEB# 32
extract_blocks Block: PEB# 35: LEB# 33
extract_blocks Block: PEB# 36: LEB# 34
extract_blocks Block: PEB# 37: LEB# 35
extract_blocks Block: PEB# 38: LEB# 36
extract_blocks Block: PEB# 39: LEB# 37
extract_blocks Block: PEB# 40: LEB# 38
extract_blocks Block: PEB# 41: LEB# 39
extract_blocks Block: PEB# 42: LEB# 40
extract_blocks Block: PEB# 43: LEB# 41
extract_blocks Block: PEB# 44: LEB# 42
extract_blocks Block: PEB# 45: LEB# 43
extract_blocks Block: PEB# 46: LEB# 44
extract_blocks Block: PEB# 47: LEB# 45
extract_blocks Block: PEB# 48: LEB# 46
extract_blocks Block: PEB# 49: LEB# 47
extract_blocks Block: PEB# 50: LEB# 48
extract_blocks Block: PEB# 51: LEB# 49
extract_blocks Block: PEB# 52: LEB# 50
extract_blocks Block: PEB# 53: LEB# 51
extract_blocks Block: PEB# 54: LEB# 52
extract_blocks Block: PEB# 55: LEB# 53
extract_blocks Block: PEB# 56: LEB# 54
extract_blocks Block: PEB# 57: LEB# 55
extract_blocks Block: PEB# 58: LEB# 56
extract_blocks Block: PEB# 59: LEB# 57
extract_blocks Block: PEB# 60: LEB# 58
extract_blocks Block: PEB# 61: LEB# 59
extract_blocks Block: PEB# 62: LEB# 60
extract_blocks Block: PEB# 63: LEB# 61
extract_blocks Block: PEB# 64: LEB# 62
extract_blocks Block: PEB# 65: LEB# 63
extract_blocks Block: PEB# 66: LEB# 64
extract_blocks Block: PEB# 67: LEB# 65
extract_blocks Block: PEB# 68: LEB# 66
extract_blocks Block: PEB# 69: LEB# 67
extract_blocks Block: PEB# 70: LEB# 68
extract_blocks Block: PEB# 71: LEB# 69
extract_blocks Block: PEB# 72: LEB# 70
extract_blocks Block: PEB# 73: LEB# 71
extract_blocks Block: PEB# 74: LEB# 72
extract_blocks Block: PEB# 75: LEB# 73
extract_blocks Block: PEB# 76: LEB# 74
extract_blocks Block: PEB# 77: LEB# 75
extract_blocks Block: PEB# 78: LEB# 76
extract_blocks Block: PEB# 79: LEB# 77
extract_blocks Block: PEB# 80: LEB# 78
extract_blocks Block: PEB# 81: LEB# 79
extract_blocks Block: PEB# 82: LEB# 80
extract_blocks Block: PEB# 83: LEB# 81
extract_blocks Block: PEB# 84: LEB# 82
extract_blocks Block: PEB# 85: LEB# 83
extract_blocks Block: PEB# 86: LEB# 84
extract_blocks Block: PEB# 87: LEB# 85
extract_blocks Block: PEB# 88: LEB# 86
extract_blocks Block: PEB# 89: LEB# 87
extract_blocks Block: PEB# 90: LEB# 88
extract_blocks Block: PEB# 91: LEB# 89
extract_blocks Block: PEB# 92: LEB# 90
extract_blocks Block: PEB# 93: LEB# 91
extract_blocks Block: PEB# 94: LEB# 92
extract_blocks Block: PEB# 95: LEB# 93
extract_blocks Block: PEB# 96: LEB# 94
extract_blocks Block: PEB# 97: LEB# 95
extract_blocks Block: PEB# 98: LEB# 96
extract_blocks Block: PEB# 99: LEB# 97
extract_blocks Block: PEB# 100: LEB# 98
extract_blocks Block: PEB# 101: LEB# 99
extract_blocks Block: PEB# 102: LEB# 100
extract_blocks Block: PEB# 103: LEB# 101
extract_blocks Block: PEB# 104: LEB# 102
extract_blocks Block: PEB# 105: LEB# 103
extract_blocks Block: PEB# 106: LEB# 104
extract_blocks Block: PEB# 107: LEB# 105
extract_blocks Block: PEB# 108: LEB# 106
extract_blocks Block: PEB# 109: LEB# 107
extract_blocks Block: PEB# 110: LEB# 108
extract_blocks Block: PEB# 111: LEB# 109
extract_blocks Block: PEB# 112: LEB# 110
extract_blocks Block: PEB# 113: LEB# 111
extract_blocks Block: PEB# 114: LEB# 112
extract_blocks Block: PEB# 115: LEB# 113
extract_blocks Block: PEB# 116: LEB# 114
extract_blocks Block: PEB# 117: LEB# 115
extract_blocks Block: PEB# 118: LEB# 116
extract_blocks Block: PEB# 119: LEB# 117
extract_blocks Block: PEB# 120: LEB# 118
extract_blocks Block: PEB# 121: LEB# 119
extract_blocks Block: PEB# 122: LEB# 120
extract_blocks Block: PEB# 123: LEB# 121
extract_blocks Block: PEB# 124: LEB# 122
extract_blocks Block: PEB# 125: LEB# 123
extract_blocks Block: PEB# 126: LEB# 124
extract_blocks Block: PEB# 127: LEB# 125
extract_blocks Block: PEB# 128: LEB# 126
extract_blocks Block: PEB# 129: LEB# 127
extract_blocks Block: PEB# 130: LEB# 128
extract_blocks Block: PEB# 131: LEB# 129
extract_blocks Block: PEB# 132: LEB# 130
extract_blocks Block: PEB# 133: LEB# 131
extract_blocks Block: PEB# 134: LEB# 132
extract_blocks Block: PEB# 135: LEB# 133
extract_blocks Block: PEB# 136: LEB# 134
extract_blocks Block: PEB# 137: LEB# 135
extract_blocks Block: PEB# 138: LEB# 136
extract_blocks Block: PEB# 139: LEB# 137
extract_blocks Block: PEB# 140: LEB# 138
extract_blocks Block: PEB# 141: LEB# 139
extract_blocks Block: PEB# 142: LEB# 140
extract_blocks Block: PEB# 143: LEB# 141
extract_blocks Block: PEB# 144: LEB# 142
extract_blocks Block: PEB# 145: LEB# 143
extract_blocks Block: PEB# 146: LEB# 144
extract_blocks Block: PEB# 147: LEB# 145
extract_blocks Block: PEB# 148: LEB# 146
extract_blocks Block: PEB# 149: LEB# 147
extract_blocks Block: PEB# 150: LEB# 148
extract_blocks Block: PEB# 151: LEB# 149
extract_blocks Block: PEB# 152: LEB# 150
extract_blocks Block: PEB# 153: LEB# 151
extract_blocks Block: PEB# 154: LEB# 152
extract_blocks Block: PEB# 155: LEB# 153
extract_blocks Block: PEB# 156: LEB# 154
extract_blocks Block: PEB# 157: LEB# 155
extract_blocks Block: PEB# 158: LEB# 156
extract_blocks Block: PEB# 159: LEB# 157
extract_blocks Block: PEB# 160: LEB# 158
extract_blocks Block: PEB# 161: LEB# 159
extract_blocks Block: PEB# 162: LEB# 160
extract_blocks Block: PEB# 163: LEB# 161
extract_blocks Block: PEB# 164: LEB# 162
extract_blocks Block: PEB# 165: LEB# 163
extract_blocks Block: PEB# 166: LEB# 164
extract_blocks Block: PEB# 167: LEB# 165
extract_blocks Block: PEB# 168: LEB# 166
extract_blocks Block: PEB# 169: LEB# 167
extract_blocks Block: PEB# 170: LEB# 168
extract_blocks Block: PEB# 171: LEB# 169
extract_blocks Block: PEB# 172: LEB# 170
extract_blocks Block: PEB# 173: LEB# 171
extract_blocks Block: PEB# 174: LEB# 172
extract_blocks Block: PEB# 175: LEB# 173
extract_blocks Block: PEB# 176: LEB# 174
extract_blocks Block: PEB# 177: LEB# 175
extract_blocks Block: PEB# 178: LEB# 176
extract_blocks Block: PEB# 179: LEB# 177
extract_blocks Block: PEB# 180: LEB# 178
extract_blocks Block: PEB# 181: LEB# 179
extract_blocks Block: PEB# 182: LEB# 180
extract_blocks Block: PEB# 183: LEB# 181
extract_blocks Block: PEB# 184: LEB# 182
extract_blocks Block: PEB# 185: LEB# 183
extract_blocks Block: PEB# 186: LEB# 184
extract_blocks Block: PEB# 187: LEB# 185
extract_blocks Block: PEB# 188: LEB# 186
extract_blocks Block: PEB# 189: LEB# 187
extract_blocks Block: PEB# 190: LEB# 188
extract_blocks Block: PEB# 191: LEB# 189
extract_blocks Block: PEB# 192: LEB# 190
extract_blocks Block: PEB# 193: LEB# 191
extract_blocks Block: PEB# 194: LEB# 192
extract_blocks Block: PEB# 195: LEB# 193
extract_blocks Block: PEB# 196: LEB# 194
extract_blocks Block: PEB# 197: LEB# 195
extract_blocks Block: PEB# 198: LEB# 196
extract_blocks Block: PEB# 199: LEB# 197
extract_blocks Block: PEB# 200: LEB# 198
extract_blocks Block: PEB# 201: LEB# 199
extract_blocks Block: PEB# 202: LEB# 200
extract_blocks Block: PEB# 203: LEB# 201
extract_blocks Block: PEB# 204: LEB# 202
extract_blocks Block: PEB# 205: LEB# 203
extract_blocks Block: PEB# 206: LEB# 204
extract_blocks Block: PEB# 207: LEB# 205
extract_blocks Block: PEB# 208: LEB# 206
extract_blocks Block: PEB# 209: LEB# 207
extract_blocks Block: PEB# 210: LEB# 208
extract_blocks Block: PEB# 211: LEB# 209
extract_blocks Block: PEB# 212: LEB# 210
extract_blocks Block: PEB# 213: LEB# 211
extract_blocks Block: PEB# 214: LEB# 212
extract_blocks Block: PEB# 215: LEB# 213
extract_blocks Block: PEB# 216: LEB# 214
extract_blocks Block: PEB# 217: LEB# 215
extract_blocks Block: PEB# 218: LEB# 216
extract_blocks Block: PEB# 219: LEB# 217
extract_blocks Block: PEB# 220: LEB# 218
extract_blocks Block: PEB# 221: LEB# 219
extract_blocks Block: PEB# 222: LEB# 220
extract_blocks Block: PEB# 223: LEB# 221
extract_blocks Block: PEB# 224: LEB# 222
extract_blocks Block: PEB# 225: LEB# 223
extract_blocks Block: PEB# 226: LEB# 224
extract_blocks Block: PEB# 227: LEB# 225
extract_blocks Block: PEB# 228: LEB# 226
extract_blocks Block: PEB# 229: LEB# 227
extract_blocks Block: PEB# 230: LEB# 228
extract_blocks Block: PEB# 231: LEB# 229
extract_blocks Block: PEB# 232: LEB# 230
extract_blocks Block: PEB# 233: LEB# 231
extract_blocks Block: PEB# 234: LEB# 232
extract_blocks Block: PEB# 235: LEB# 233
extract_blocks Block: PEB# 236: LEB# 234
extract_blocks Block: PEB# 237: LEB# 235
extract_blocks Block: PEB# 238: LEB# 236
extract_blocks Block: PEB# 239: LEB# 237
extract_blocks Block: PEB# 240: LEB# 238
extract_blocks Block: PEB# 241: LEB# 239
extract_blocks Block: PEB# 242: LEB# 240
extract_blocks Block: PEB# 243: LEB# 241
extract_blocks Block: PEB# 244: LEB# 242
extract_blocks Block: PEB# 245: LEB# 243
extract_blocks Block: PEB# 246: LEB# 244
extract_blocks Block: PEB# 247: LEB# 245
extract_blocks Block: PEB# 248: LEB# 246
extract_blocks Block: PEB# 249: LEB# 247
extract_blocks Block: PEB# 250: LEB# 248
extract_blocks Block: PEB# 251: LEB# 249
extract_blocks Block: PEB# 252: LEB# 250
extract_blocks Block: PEB# 253: LEB# 251
extract_blocks Block: PEB# 254: LEB# 252
extract_blocks Block: PEB# 255: LEB# 253
extract_blocks Block: PEB# 256: LEB# 254
extract_blocks Block: PEB# 257: LEB# 255
extract_blocks Block: PEB# 258: LEB# 256
extract_blocks Block: PEB# 259: LEB# 257
extract_blocks Block: PEB# 260: LEB# 258
extract_blocks Block: PEB# 261: LEB# 259
extract_blocks Block: PEB# 262: LEB# 260
extract_blocks Block: PEB# 263: LEB# 261
extract_blocks Block: PEB# 264: LEB# 262
extract_blocks Block: PEB# 265: LEB# 263
extract_blocks Block: PEB# 266: LEB# 264
extract_blocks Block: PEB# 267: LEB# 265
extract_blocks Block: PEB# 268: LEB# 266
extract_blocks Block: PEB# 269: LEB# 267
extract_blocks Block: PEB# 270: LEB# 268
extract_blocks Block: PEB# 271: LEB# 269
extract_blocks Block: PEB# 272: LEB# 270
extract_blocks Block: PEB# 273: LEB# 271
extract_blocks Block: PEB# 274: LEB# 272
extract_blocks Block: PEB# 275: LEB# 273
extract_blocks Block: PEB# 276: LEB# 274
extract_blocks Block: PEB# 277: LEB# 275
extract_blocks Block: PEB# 278: LEB# 276
extract_blocks Block: PEB# 279: LEB# 277
extract_blocks Block: PEB# 280: LEB# 278
extract_blocks Block: PEB# 281: LEB# 279
extract_blocks Block: PEB# 282: LEB# 280
extract_blocks Block: PEB# 283: LEB# 281
extract_blocks Block: PEB# 284: LEB# 282
read Error: Block ends at 37486592 which is greater than file size 37355540
extract_blocks Fatal: PEB: 285: Bad Read Offset Request

here the file

https://repository.ilpuntotecnicoeadsl.com/index.php?dir=Ansuel/&file=2C0000.ubi

**Comment by jrspruitt** [comment]
Hi Ansuel,

If this is from a NAND dump or something similar, that generally means the
dump is not complete, and there is some data left on the device that was
not captured. It could also mean there is some corrupted data, that is
throwing off ubi_reader as it jumps from block to block.

-Jason

**Comment by Ansuel** [comment]
Actually this is from a downloaded firmware extracted from binwalk... It shouldn't be corrupted as normally this should be flashed on a clean nand.
Any idea?

**Comment by jrspruitt** [comment]
I'm not really sure then, so far it has always been an incomplete
image that causes this. If you have the file it was extracted from,
you might try just running that through ubi_reader. You may have to
set the start address, if there are false positives it finds though.
