### ISSUE TITLE
Refactor sort.by_image_seq

### ISSUE THREAD

**Issue by rmspeers** [jrspruitt/ubi_reader#24]
I would like to suggest a refactor to sort.by_image_seq to more directly make it represent a filtering function, which is what it implements based on the current code.

I am happy to submit a PR to do this, and we could just change the internals of the function and not the signature at all. I have tested that on my images at least, the results match -- and the intent is the same as well. This should be a super minor change but just wanted to contribute it as I get used to the internals of ubi_reader.

**Comment by rmspeers** [comment]
The diff at https://github.com/jrspruitt/ubi_reader/compare/master...rmspeers:feature/24-refactor-sort?expand=1 is not the actual PR that would be submitted, but it is shown to indicate equivalency and allow easy comparison of the results in the absence of an existing unit test framework in the project. If @jrspruitt concurs, I will submit a clean PR.

**Comment by rmspeers** [comment]
The code I'm proposing should work on both Py2.7/3 as I've called list after the filter function, and in general the recommendation is to use filter for performance reasons but I haven't done timing on this specific change. I'll clean up the PR and submit for your review.

**Comment by jrspruitt** [comment]
Thank you,
When I get some time I'll test this, and push it.

-Jason

**Comment by jrspruitt** [comment]
Merged thank you.
-Jason
