### ISSUE TITLE
Block ends after file

### ISSUE THREAD

**Issue by BorjanEch0** [jrspruitt/ubi_reader#31]
Dear Developer, i seem to be getting this error and i just cant fix it, can you please help.. when extracting an image i get this error: 
Extracting files to: ubifs-root
read Error: Block ends at 1209249656 which is greater than file size 42029056
index Fatal: LEB: 10, UBIFS offset: 1290104, error: Bad Read Offset Request

**Comment by jrspruitt** [comment]
Sorry I don't have the time to help with individual extractions anymore, but this is usually either a NAND dump that is not complete or includes the OOB data, or it's possible the manufacturer of the image is using something non-standard.

-Jason

**Comment by BorjanEch0** [comment]
Dear Jason, i understand, i used the testing branch extract_data tool and it helped me recover what i need. Thank you.

**Comment by ning1022** [comment]
@BorjanEch0    where can download " testing branch extract_data tool " , i meet the same problem。
```
root@ning-virtual-machine:~# ubireader_extract_files jy
read Error: Block ends at 553725488 which is greater than file size 553648128
extract_blocks Fatal: PEB: 3895: Bad Read Offset Request
root@ning-virtual-machine:~# ubireader_list_files jy
read Error: Block ends at 553725488 which is greater than file size 553648128
extract_blocks Fatal: PEB: 3895: Bad Read Offset Request
root@ning-virtual-machine:~# ubireader_extract_images jy
read Error: Block ends at 553725488 which is greater than file size 553648128
extract_blocks Fatal: PEB: 3895: Bad Read Offset Request
root@ning-virtual-machine:~# ubireader_utils_info jy
read Error: Block ends at 553725488 which is greater than file size 553648128
extract_blocks Fatal: PEB: 3895: Bad Read Offset Request
root@ning-virtual-machine:~# ubireader_display_info jy
read Error: Block ends at 553725488 which is greater than file size 553648128
extract_blocks Fatal: PEB: 3895: Bad Read Offset Request
```

**Comment by jrspruitt** [comment]
ning1022,

Most of the time this is caused by an incomplete NAND dump, or the OOB data was not removed from the NAND dump. To switch to testing branch, you need to change the branch with git after you clone the repo. Or change the branch in the Github UI before using the download feature.

-Jason

**Comment by ning1022** [comment]
I got this extract_data , but when I run the extract_data, I can get a lot of  0 byte files and some errors.


```
No data found in node {'ino': UBIFS Ino Node}
No data found in node {'ino': UBIFS Ino Node}
extract_dents Warn: FILE Fail: 'ino'
No data found in node {'ino': UBIFS Ino Node}
extract_dents Warn: FILE Fail: 'ino'
No data found in node {'ino': UBIFS Ino Node}
extract_dents Error: inum: 2186 not found in inodes
extract_dents Warn: FILE Fail: 'ino'
No data found in node {'ino': UBIFS Ino Node}
No data found in node {'ino': UBIFS Ino Node}
No data found in node {'ino': UBIFS Ino Node}
extract_dents Warn: FILE Fail: 'ino'
No data found in node {'ino': UBIFS Ino Node}
extract_dents Error: inum: 2197 not found in inodes
No data found in node {'ino': UBIFS Ino Node}
No data found in node {'ino': UBIFS Ino Node}
extract_dents Error: inum: 2200 not found in inodes
extract_dents Error: inum: 2203 not found in inodes
No data found in node {'ino': UBIFS Ino Node}
extract_dents Error: inum: 2210 not found in inodes
No data found in node {'ino': UBIFS Ino Node}
```

**Comment by jrspruitt** [comment]
ning1022,

More often than not, issues like this are caused by an incomplete NAND dump, or problems with the UBI image. With a NAND dump there could be other issues that arise such as a bit error not corrected. It's hard to know with out looking at the data you're using.

-Jason
