### ISSUE TITLE
Porting to Python 3

### ISSUE THREAD

**Issue by 0xd3xt3r** [jrspruitt/ubi_reader#32]
any plans on porting the library to python3 ?

**Comment by jrspruitt** [comment]
It should work with Python 3, but it has not been tested on some of the newer versions of 3.
-Jason

**Comment by 0xd3xt3r** [comment]
Tired to testing it with python 3.5.7 didn't work.
Syntax issues with print method and Exception syntax

**Comment by jrspruitt** [comment]
The latest version has worked okay for me on 3.5.3, not sure what they would have changed. I'll look into it.
-Jason

**Comment by 0xd3xt3r** [comment]
I dought it will work on any python3 version due to following syntax errors :
1. `print 'Hello' ` which in python3 is `print("Hello")`
1. `except Exception, e:` which in pytho3 is `exception Exception as e`
1. other list and generator issues

**Comment by jrspruitt** [comment]
What lines are those on? Those things should have all been fixed when it was ported to 3. Where did you get your copy from pip? or github?

**Comment by 0xd3xt3r** [comment]
Sorry about not posting the whole problem, current version working just fine with the python3. 

I checkout to  the old version commit : 0955e6b95f07d849a182125919a1f2b6790d5b51, as there were some issue with the current version.

I am able to extract the filesystem from the firmware image with the earlier version(commit mentioned above) and I am have trouble extracting the filesystem from the same image with the latest version. The error which am getting is as follows:

> read Error: Block ends at 39608400 which is greater than file size 39499289
> extract_blocks Fatal: PEB: 242.0: Bad Read Offset Request

**Comment by jrspruitt** [comment]
Try using the -w command line flag with the new version, it should just warn about the problem instead of stopping.

**Comment by 0xd3xt3r** [comment]
doing little digging... I traced the error to line 112 of ubi_io.py file and commenting the exception image was able to extract the filesystem from the image. ( on the latest version of the code)

**Comment by 0xd3xt3r** [comment]
Oh sweet it works

**Comment by jrspruitt** [comment]
Good to hear.

**Comment by 0xd3xt3r** [comment]
Thanks, for the quick response
