### ISSUE TITLE
extract_files not preserving set-user-ID or set-group-ID permission bits

### ISSUE THREAD

**Issue by huydng** [jrspruitt/ubi_reader#33]
In _set_file_perms function in ubireader/ubifs/output.py, chown may be clearing set-user-ID or set-group-ID permission bits

```
def _set_file_perms(path, inode):
    os.chmod(path, inode['ino'].mode)
    os.chown(path, inode['ino'].uid, inode['ino'].gid)
```

For example, a file's original permission -rw**s**r-xr-x may become -rw**x**r-xr-x after extraction.

In order to preserve set-user-ID or set-group-ID permission bits, chmod should be called _after_ chown.

**Comment by jrspruitt** [comment]
Hi huydng,
Thank you for pointing this out, I swapped the commands.
-Jason
