### ISSUE TITLE
How to handle ubi dump with only one volume table ?

### ISSUE THREAD

**Issue by dummys** [jrspruitt/ubi_reader#36]
Hi,

Is there a way to extract an image with only one volume table block ? I lazy patched your code:

https://github.com/jrspruitt/ubi_reader/blob/5579cb8acf63c62e7c7be8ab342ddf555cd3b001/ubireader/ubi/__init__.py#L152 to 1, and patched everywhere where you use `layout_list[2]`. So the tool is creating the virtual image now, but fail at this:

```
group_pairs Layout blocks found at PEBs: [[438]]
description Create Volume: bootdata, ID: 0, Block Cnt: 1
description Create Volume: unitdata, ID: 1, Block Cnt: 1
description Create Volume: caldata, ID: 12, Block Cnt: 1
description Create Volume: caldata_backup, ID: 13, Block Cnt: 1
description Created Image: 1315753792, Volume Cnt: 4
leb_virtual_file read loc: 140251136, size: 24
UBIFS UBIFS Common Header file addr: 140251136
	UBIFS Common Header
	---------------------
		crc: 0x2000
		errors: 
		group_type: 101
		len: 1886220099
		magic: 684539205
		node_type: 114
		padding: 'ss'
		sqnum: 3
```
So there is somewhere that the Common header is not at the correct offset, I'm trying to understand your code on how to discover Super block to try to understand where is the error.

**Comment by jrspruitt** [comment]
Hi dummys,

It shouldn't be a problem, the only reason there is two is for redundancy if something goes wrong with a UBIFS write to those blocks IIRC. I believe all you would need to do, is remove the < 2 check, and things should work. It's been a while since I looked over this, but I'm pretty sure layout_list[2] is the list of data blocks associated with the pair of layout blocks. The second layout block is really only used to check if there are two of them which is per UBI specifications.

-Jason

**Comment by dummys** [comment]
If I remove the <2 check, then I get other error when you use the
layout[2], I get an index out of range. Can give you exactly the error on
monday.

Le sam. 16 mai 2020 à 05:38, Jason Pruitt <notifications@github.com> a
écrit :

**Comment by dummys** [comment]
To circumvent my issue, I manually copied at the end of the ubi file a copy
of the layout. Then when I want to extract files with the script I get this
error:

```
UBIFS UBIFS Common Header file addr: 140251136
UBIFS Common Header
---------------------
crc: 0x2000
errors:
group_type: 101
len: 1886220099
magic: 684539205
node_type: 114
padding: 'ss'
sqnum: 3

UBIFS Fatal: Super block error: Wrong node type.
```

I think somewhere I should have something that make your parser go wrong
when searching for super block node I think.

**Comment by jrspruitt** [comment]
It is possible to use other file systems on top of UBI, have you tried just using ubireader_extract_images and see if it's actually UBIFS or instead some other type?

**Comment by dummys** [comment]
Yes it's "Compressed ROMFS". 
I think I found a bug in your tooling see line :
https://github.com/jrspruitt/ubi_reader/blob/930f037088e1636da5e4f8f2449e5820cca31de7/ubireader/ubi/block/layout.py#L64

You are returning the same array that you take as parameter, I think you'll want to return `layout_pair` right ?

**Comment by jrspruitt** [comment]
ubi_reader only supports extracting UBIFS file systems, I'm not sure what you need to extract the files in a Compressed ROMFS, you might check binwalk.

The layout_pairs looks wrong, and could probably be written to make it a little clearer, python doesn't make a new copy of the object in the for loop, so when it gets returned, it's been modified, where it looks like nothing happened to it.

**Comment by dummys** [comment]
Ok I see, thanks.
I just come back from the last thread and thinking about changing the `< 2` to make it works with only one vtbl, it can not work due to this code:
https://github.com/jrspruitt/ubi_reader/blob/930f037088e1636da5e4f8f2449e5820cca31de7/ubireader/ubi/image.py#L30

Here you are using 2 to locate the block list and if they were only one block with vtbl, then you will fail all the remaining code that will use the index 2 of the table.

**Comment by jrspruitt** [comment]
It's a little confusing there also, layout_info[0] and layout_info[1] are layout blocks, where layout_info[2] is the list of data blocks associated with those layout/vtbl blocks.

**Comment by dummys** [comment]
yes but If you have only one vtbl, then there is no more 2 indexes, there is only layout_info[0,1,] because otherwise layout_info[0,1] =  vtbl block and layout_info[2] = blocks list

**Comment by jrspruitt** [comment]
Oh okay, I see what you mean there.
