### ISSUE TITLE
The UBIFS Version is now 5

### ISSUE THREAD

**Issue by jrspruitt** [jrspruitt/ubi_reader#41]
There has been some changes, notably in the Super Block and Master Node structs, which includes some new entries, that enable an HMAC check in the scan function.

There may be other changes that need to be found, understood and implemented.

-Jason

**Comment by richardweinberger** [comment]
FWIW, to read UBIFS v4 you can ignore all these fields.
Only if you want to support encrypted or authenticated UBIFS they are interesting.
Please see the commit logs for the gory details. :-)
Feel free to ask me if you have questions.

**Comment by jrspruitt** [comment]
Hi Richard Weinberger,

Thanks for letting me know what this was about. I'll have to investigate further if this is worthwhile/possible to support.

-Jason
