### ISSUE TITLE
get_newest() PEB selection is broken

### ISSUE THREAD

**Issue by richardweinberger** [jrspruitt/ubi_reader#45]
You cannot simply compare `sqnum` of volume id headers.
To find the correct PEB you need to honor `copy_flag` and `data_crc` too.
Otherwise an image takem while UBI did wear leveling or atomic LEB update (which UBIFS does commonly) will result
into broken LEB->PEB mappings and corrupted volumes.

**Comment by jrspruitt** [comment]
Hi Richard Weinberger,

Thank you for explaining this, when I get some time I'll start implementing these.

-Jason

**Comment by jrspruitt** [comment]
I believe this is fixed now with the ubi/blocks/_init_.py( rm_old_blocks) function.

**Comment by richardweinberger** [comment]
Almost. :-)
Please see https://github.com/jrspruitt/ubi_reader/commit/502468bc52ab329d00961a4fa356b87c172c34e4#r83177084
