### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by derasd** [jrspruitt/ubi_reader#5]
Hello Jason,

I'm trying to extract a UBI filesystem copied directly from a NAND flash. Unfortunately I'm struggling with the following error.

```
~/ubi$ ubireader_extract_files -l ubi.img
[...]
extract_blocks Block: PEB# 2117: LEB# -1
extract_blocks Block: PEB# 2118: LEB# -1
group_pairs [[690]]
group_pairs [[690, 691]]
group_pairs [[690, 691, 2102]]
group_pairs [[690, 691, 2102, 2103]] 
Traceback (most recent call last):
  File "/usr/local/bin/ubireader_extract_files", line 4, in <module>
    __import__('pkg_resources').run_script('ubi-reader==0.4', 'ubireader_extract_files')
  File "/home/derasd/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/derasd/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ubi_reader-0.4-py2.7.egg/EGG-INFO/scripts/ubireader_extract_files", line 132, in <module>
    
  File "build/bdist.linux-x86_64/egg/ubireader/ubi/__init__.py", line 78, in __init__
  File "build/bdist.linux-x86_64/egg/ubireader/ubi/image/__init__.py", line 31, in __init__
TypeError: 'int' object is not iterable
```

The full verbose output was too big for pastebin, so here is the -l output:
http://pastebin.com/nsuanYBm 

And here I uploaded the whole flashdump:
http://www.megafileupload.com/b66i/ubiFlashFile

Do you have any idea what is going wrong?

Best regards,
Phil

**Comment by jrspruitt** [comment]
Hi Phil,

It looks like there are four layout blocks, generally there should be 2, which are both the same. All four are associated with the same image sequence, so the script gets confused. I'm guessing since this is a NAND dump, that maybe UBI had created new ones for some reason. 

The main problem here is, ubi_reader can't handle certain things about a UBI file system that has been used. If the UBI file system is in pristine condition, it'll should work, but unfortunately there are things that can happen it just can't handle like the UBI driver does. This is a very non-trivial fix, and more a feature, that should be included at some point.

For your case specifically you can fix the code up a bit, to get your image extracted.
You'll need to find where ubireader/ubi/image/__init__.py is installed and at line 29 change

        self.version = blocks[layout_info[0]].ec_hdr.version
        self._block_list = layout_info[2]

to this

        self.version = blocks[layout_info[0]].ec_hdr.version
        del layout_info[2]
        del layout_info[2]
        self._block_list = layout_info[2]

That isn't a misprint, delete the 2nd element twice, this will take out the second pair of layout blocks and get everything where they need to be.

Thanks for providing the image, when I manage to get to including the error checks and dealing with the journaling and what not, this will come in useful for testing.

-Jason

**Comment by derasd** [comment]
Hello Jason,
Thank you very much for this super fast fix! It does indeed extract without error. 

Nevertheless the output is a bit disappointing because it looks quite empty. Some system files, busybox, libraries but nothing vendor specific. 
For example, when I search the original dump for the string "Premium" (which is unlikely to be contained in a Linux system file) I get 8 matches whereas in the extracted files there is none.

So I strongly assume that not everything gets extracted correctly but the program doesn't give me any errors.

Do you have an idea?

Best regards,
Phil

**Comment by jrspruitt** [comment]
Hi Phil,

It looks like there is actually two images. ubi_reader gets confused cause they should have different image_seq numbers. I'm not sure what would cause this, although I do think its come up before, but is pretty rare.
To get at the second image, delete the first element of the layout_info list, this will use the second set of layout table blocks, I then got what looks like two different volumes, one is another RootFS and the other looks to be some vendor files.

    self.version = blocks[layout_info[0]].ec_hdr.version
    del layout_info[0]
    del layout_info[0]
    self._block_list = layout_info[2]

-Jason

**Comment by derasd** [comment]
I thought about having two images but I tried with del layout_info[1] but that gave me the same output.
But with the [0] it works perfectly.

Thank you so much!

**Comment by iTuneDVR** [comment]
Hi!
Same problem with data from nand flash
ubireader_extract_images -l ubi.img
....
extract_blocks PEB: 509.0 has possible issue EC_HDR [], VID_HDR [crc]
extract_blocks Block: PEB# 510.0: LEB# 1
extract_blocks Block: PEB# 511.0: LEB# 6
group_pairs Layout blocks found at PEBs: [[481.0, 510.0], [77, 78, 192, 193], [437.0, 447.0], [404.0, 415.0]]
description Create Volume: b'log', ID: 0, Block Cnt: 7
description Created Image: 730467828, Volume Cnt: 1
Traceback (most recent call last):
  File "/usr/local/bin/ubireader_extract_images", line 138, in <module>
    ubi_obj = ubi(ufile_obj)
  File "/usr/local/lib/python3.5/dist-packages/ubireader/ubi/__init__.py", line 166, in __init__
    self._images.append(image(self.blocks, layout_infos[i]))
  File "/usr/local/lib/python3.5/dist-packages/ubireader/ubi/image.py", line 32, in __init__
    self._start_peb = min(layout_info[2])
TypeError: 'int' object is not iterable

try add this 1 time, 2 time with [0] [1] [2]
del layout_info[0]

_error with 1 time del_

 File "/usr/local/lib/python3.5/dist-packages/ubireader/ubi/image.py", line 31, in __init__
    self._block_list = layout_info[2]
IndexError: list index out of range

_error with 2 time del_

  File "/usr/local/lib/python3.5/dist-packages/ubireader/ubi/image.py", line 31, in __init__
    del layout_info[2]
IndexError: list assignment index out of range

What do you advise?

**Comment by jrspruitt** [comment]
Hi iTuneDVR,
Usually the problem with data taken from NAND is an incomplete dump, or the problem that the error correction normally handled by the NAND driver is not performed, which can make it impossible for ubi_reader to sort through the data if there are errors present.

I do notice the CRC is failing, if this is the case for all PEBs that leaves the chance the manufacturer of the device has made changes to the UBI driver, which is not uncommon. If this is the case, you'll need to figure out what changes were made, and implement them in ubi_reader if necessary, or hope perhaps you can ignore the errors.

It also could be that there is multiple UBI images present, there looks to be several layout block, which could confirm this. You might try attempting to manually separate out the images, to help prevent any confusion for ubi_reader.

-Jason

**Comment by iTuneDVR** [comment]
Jason!
Thank you for your prompt response.
The image of the nand dump is complete without loss and the device is working.
Of course, there may be some problems with the data, but until this point your tool has helped to receive data repeatedly.
Perhaps in the functional it is necessary to add a mode of forced disclosing or ignoring of errors, search of new chains, etc.
If possible, I'll try to get data from another similar working device and see how it is.
Thank you for you work!

**Comment by jrspruitt** [comment]
If you switch to the "testing" branch, there is a tools/ directory that has some custom code I've used in the past for attempting to extract data from broken images. One thing to note is it is for Python 2, as the branch has not been updated to handle 3 yet. This route generally takes a fairly good understanding of how UBI/UBIFS works as ubi_reader is used more as a module for creating custom tools to attempt getting around data issues.

You can also check ubireader/debug.py, and comment out the sys.exit calls, or try the -w flag on the command line.

In cases like this, I find it very useful to install ubi_reader with "python setup.py develop" this allows you to edit the code to your needs, with out having to install it after every change.

-Jason

**Comment by iTuneDVR** [comment]
Jason!
Thank you, wiil try.
Using TTL2USB & connect to TTL find NAND problem at the boot log.
Data is not so important, but nevertheless.

**Comment by rmspeers** [comment]
Given I am running into this as well, may I suggest a change for consideration in image.py?

Basically, in initialization, we would know that the rest of the code can't handle cases of not exactly two blocks. Thus, although these cases may exist and a later feature as @jrspruitt  has mentioned above could handle them, at this time we would at least handle the scenario as gracefully as possible with the current features?

The change would be to add to the top of the description init function the following:
```
        if len(layout_info) > 3:
            to_delete = len(layout_info) - 3
            log(description, 'layout_info size adjusting, likely {} extra blocks which we will now delete.'.format(to_delete))
            del layout_info[2:2+to_delete]
```

If acceptable, I am happy to open a PR to provide this.

**Comment by jrspruitt** [comment]
Hi rmspeers,

Thank you for the suggestion, but I believe this issue is a damned if you do, damned if you don't situation. And I've sided with letting it fail, to alert the user, something isn't quite normal about their image/data dump. That there are extra layout blocks indicates something is wrong, in one of the above cases it looks like, non-unique image sequence numbers. So further work on the data is required, to get it into a state ubi_reader can work with successfully. If we just cut out extra layout blocks, I fear it would just skip over issues, people should be alerted too. Also in that case, I believe the layout blocks could get associated with the wrong data blocks, causing chaos.

-Jason

**Comment by rmspeers** [comment]
Would you consider a force flag, and when force is not triggered, then at least have this log a warning even if it doesn't delete it (instead of falling through to the integer exception)?

In my use case, I need to be able to get whatever data I can out, which in this case means ignoring the extra blocks.

I'm happy to look more at how to parse the layout blocks if you want to point me to the relevant part of the spec - I don't have the depth of background you do on UBI but I can look into it.

**Comment by jrspruitt** [comment]
This would be a good place to have a "fatal error" that halts everything nicely, then use one of the flags in the settings.py file, if you want to avoid it, I think. I should probably put some of these settings on the command line, for ease of use, or at least document them. I'll work on this.

Not sure if you know this but the _testing_ branch /tools/ has some custom script examples for dealing with broken images, it might help in your case if it is being difficult. It is a bit behind _master_ and is py2 only. It might help also if you're wanting to learn some more of the internals. If you want to know more, the Linux source (mtd-utils) is the best I found, other than a few overviews, there wasn't a definitive document explaining it all, atleast when I was doing this.

Would it be possible to get a copy of the image you are working with? I keep a collection of them to test against, out of the ordinary ones help the most. If not I completely understand.

Thanks,
-Jason

**Comment by rmspeers** [comment]
Thanks - image provided separately. I can utilize the main branch if we resolve this as I think you're suggesting:
- default behavior is to throw fatal
- CLI flag can override and delete excess records (or flag set in settings.py)

Let me know if you want me to work on any of this, else will keep an eye out for your updates.
