### ISSUE TITLE
decompress Warn: LZO Error: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by danyhm** [jrspruitt/ubi_reader#52]
Hello,

I get this error with python 3.10 in windows , python-lzo 1.12 installed from the wheels in here
https://www.lfd.uci.edu/~gohlke/pythonlibs/

I think I had used it with python 3.8 and there was no problem.

**Comment by jrspruitt** [comment]
Hi danyhm,
Thanks for the info, looks like you already reported it to python-lzo. From what I can tell it's a new requirement of 3.10.
-Jason

**Comment by danyhm** [comment]
Hi,
yes i double checked and it works fine with python 3.8
