### ISSUE TITLE
Version bump request

### ISSUE THREAD

**Issue by oliv3r** [jrspruitt/ubi_reader#53]
Hey @jrspruitt,

any thoughts on when to expect a nother version bump? Last version is 3 years old and there's been quite some activity. Maybe a small bump is fair?

**Comment by jrspruitt** [comment]
Hi oliv34,
I guessed you were talking about a new release? That was way behind, I seemed to have forgotten them, thank you.
-Jason

**Comment by oliv3r** [comment]
New tag == new release yeah :) sorry; thanks Feel free to close this issue with the new release :)
