### ISSUE TITLE
ubi image extracting problem 

### ISSUE THREAD

**Issue by blackpk** [jrspruitt/ubi_reader#59]
read Error: LEB: 17 is corrupted or has no data.
extract_files Error: Bad Read Offset Request

**Comment by jrspruitt** [comment]
Sounds like possibly an incomplete data dump.

**Comment by blackpk** [comment]
https://mega.nz/file/slgigCgT#0_jgHLuTDVPsMlNqKqWmlyDX6vk1Ujk_uEvqMo_0170

**Comment by blackpk** [comment]
Some data add Russian specially file pack for ubi readers don't unpacking system if try -w -i file unpack but my required data missing

**Comment by blackpk** [comment]
https://www.mediafire.com/file/220znqr0pt2ow0e/1st.rar/file

**Comment by jrspruitt** [comment]
Hi blackpk,

Something is wrong, but I could not figure out what exactly. It did not seem like ubi_reader was picking up an older block, but the image is certainly wanting an LEB (17) that does not exist. There is a 27 and it proceeds to count up from there. It is not unheard of, that a manufacturer will mess around with UBI to prevent extraction, although it is rare. Sorry I could not help.

-Jason

**Comment by blackpk** [comment]
Thx a lot
