### ISSUE TITLE
extract_files needs better error handling

### ISSUE THREAD

**Issue by taylornelson** [jrspruitt/ubi_reader#6]
Or a switch to keep processing  dents if one is corrupt 
changing the error handling to be as:
        error(extract_files, 'MostlyFatal', '%s' % e)
allowed me to extract a second volume from a ubi image

**Comment by jrspruitt** [comment]
This is something I've manually done in the past, it should be a feature. When I get a chance I'll add it in.

**Comment by jrspruitt** [comment]
Finally got some time. I added command line option -w, --warn-only-block-read-errors, which allowed me to keep extracting files when there was certain errors. Some files will be missing or possibly corrupted, but at least gets what is available. Also added -i, --ignore-block-header-errors, which is more for displaying info, as it will include blocks for display that are probably not used, but it is possible they are falsely marked as such.
