### ISSUE TITLE
Python3 is required

### ISSUE THREAD

**Issue by lthiery** [jrspruitt/ubi_reader#60]
Under python2, the following error occurs:
```
Extracting files to: ubifs-root
extract_files Error: 'module' object has no attribute 'commonpath'
```

**Comment by AT0myks** [comment]
This seems to come from [`c6a1272`](https://github.com/jrspruitt/ubi_reader/commit/c6a1272b178a4a2a04cfc88c87f6e195b16eddb5#diff-9701fbf2239b9a1296d436ca2d8e6b4683ec595eaed75eba504015f9cd187f4cR32). `os.path.commonpath` indeed [requires](https://docs.python.org/3/library/os.path.html#os.path.commonpath) Python 3.5+. Unless you really need v0.8.2 you can use v0.8.0 where this code wasn't present.

**Comment by lthiery** [comment]
It's not a big deal on my end. I just ran it in Python3.

**Comment by lthiery** [comment]
#62 opened to update docs

**Comment by jrspruitt** [comment]
Hi lthiery,

Thank you for pointing this out. I will have to consider Python 2 support going forward, as it is EOL, and I imagine issues like this will only get worse going forward. I would imagine ubi_reader is probably used on newer OS's where python 3 is going to be supported, instead of older hardware.

-Jason

**Comment by lthiery** [comment]
I would agree with dropping Python2 support. Generally, this package seems useful in build and development systems which should have no problem upgrading to Python2.

**Comment by jrspruitt** [comment]
I ended up getting sucked into a different issue, that only showed up when comparing extractions from Python 2 vs 3. I ended up fixing it so Python 2 works in the latest commit.

-Jason

**Comment by lthiery** [comment]
You're a kind person! Thanks
