### ISSUE TITLE
can't unpack ubi pakage

### ISSUE THREAD

**Issue by Ruomengsiming** [jrspruitt/ubi_reader#69]
When I try to unpack the ubi file, it return this error, I can't understand
han@OwnerLaptop:~/xiaomi/bin/_miwifi_rc01_firmware_1.0.59.bin.extracted$ ubireader_extract_images 324.ubi 
Traceback (most recent call last):
  File "/usr/local/bin/ubireader_extract_images", line 4, in <module>
    __import__('pkg_resources').run_script('ubi-reader==0.8.5', 'ubireader_extract_images')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1452, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/ubireader_extract_images' not found in metadata at '/usr/local/lib/python3.8/dist-packages/ubi_reader-0.8.5.dist-info'

**Comment by jrspruitt** [comment]
Hi @Ruomengsiming,

I've never seen this before, what Operating System/Distribution are you using, and how did you install it?

-Jason

**Comment by Ruomengsiming** [comment]
Thanks. I have found why the question will be, because when i have run 'sudo python setup.py install',also run 'sudo pip install ubi_reader' again, now I reinstall it, My question is resoved
