### ISSUE TITLE
struct error

### ISSUE THREAD

**Issue by beppe9000** [jrspruitt/ubi_reader#7]
I'm trying to see info on a ubi/ubifs dump but I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ubireader_display_info", line 5, in <module>
    pkg_resources.run_script('ubi-reader==0.4', 'ubireader_display_info')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ubi_reader-0.4-py2.7.egg/EGG-INFO/scripts/ubireader_display_info", line 112, in <module>

  File "build/bdist.linux-x86_64/egg/ubireader/ubi/__init__.py", line 52, in __init__
  File "build/bdist.linux-x86_64/egg/ubireader/ubi/block/__init__.py", line 124, in extract_blocks
  File "build/bdist.linux-x86_64/egg/ubireader/ubi/block/__init__.py", line 65, in __init__
  File "build/bdist.linux-x86_64/egg/ubireader/ubi/headers/__init__.py", line 49, in __init__
struct.error: unpack requires a string argument of length 64
```

What is the cause? Any step that I could try?

**Comment by jrspruitt** [comment]
Hi,
On storage dumps it can be kind of hit or miss on how well it works. Try the very verbose option. That should tell you which block it failed at at least. My experience has been the dump is usually not complete, and the end of the image is cut off. Or in some cases the manufacturer has done something out of specifications.

-Jason

**Comment by beppe9000** [comment]
I ran it with verbose and got this:

```
UBI_File read loc: 103153664, size: 131072
extract_blocks Block: PEB# 787: LEB# 562
extract_blocks file addr: 103153664
        Block: PEB# 787: LEB# 562
        ---------------------
                File Offset: 103153664
                PEB #: 787
                LEB #: 562
                Block Size: 131072
                Internal Volume: False
                Is Volume Table: False
                Is Valid: True

                Erase Count Header
                ---------------------

                VID Header Header
                ---------------------


UBI_File read loc: 103284736, size: 131072
```

Next there is the stacktrace i put in the op.

Is `UBI_File read loc: 103284736` the position? Is it expressed in bytes?

**Comment by jrspruitt** [comment]
Yes that is the position in bytes of the block it is trying to read, is your image bigger than that by at least 131072 bytes?

**Comment by beppe9000** [comment]
I assumed those are bytes and went to look in the file. At that position is this:
```
55 42 49 23 01 00 00 00 00 00 00 00 00 00 00 26 | UBI#...........& | 䉕⍉.....☀
00 00 08 00 00 00 10 00 68 73 91 80 00 00 00 00 | ........hs‘€.... | ....獨肑..
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | ........
00 00 00 00 00 00 00 00 00 00 00 00 BA 28 52 76 | ............º(Rv | ......⢺癒
```
Followed by 1984 bytes of zeroes.

Is this another empty image? A footer of th emain image or anything else?

**Comment by jrspruitt** [comment]
Hmm, off hand that looks correct, can you provide a link to the image? Would be easier for me to diagnose it.

**Comment by beppe9000** [comment]
Sure, here it is : [04-1c00000a7ffffff.zip](https://github.com/jrspruitt/ubi_reader/files/499120/04-1c00000a7ffffff.zip)

**Comment by jrspruitt** [comment]
Hi,

Best I can tell is the image isn't complete. The image size is 103286784 bytes, the block that fails is located at 103284736 bytes into the image. At that location it will try and read 131072 bytes of data, but according to the image size there is only 2048 bytes beyond that point till the end of the file. Which leaves it short at least 129024 bytes. It may in fact be more, but to complete this block read it is that much short.

I tried getting around the error and letting it continue to run, but it only created garbage UBIFS files. So if you can, make another dump making sure you get all the way to the very end of the storage device otherwise I don't think there is a lot that can be done.

-Jason

**Comment by beppe9000** [comment]
Ok, I did't do this dump myself so I will ask the original author. Thanks! I'll let you know if I am able to read it then.
